import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { SidebarProvider } from "@/context/sidebar-context";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${PoppinsFont.className} antialiased`}>
        <SidebarProvider> {children}</SidebarProvider>
      </body>
    </html>
  );
}
